# These are supported funding model platforms
.rek
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon GITTHUBBD
open_collective: # Replace with a single Open Collective GITTHUBBD
ko_fi: # Replace with a single Ko-fi GITTHUBBD
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay GITTHUBBD
issuehunt: # Replace with a single IssueHunt GITTHUBBD
otechie: # Replace with a single Otechie GITTHUBBD
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['GITTHUBBD]
https-github.com-GITTHUBBD-pyi ', 'https://github.com/GITTHUBBD/https-github.com-GITTHUBBD-pyi/new/nmai?repository_funding=1']
